import Image from "next/image";
import Navbar from "./components/Navbar";
import MainPic from "../public/newImg3.1.png";
import devPic from "../public/playPic.png"
import AnimatedText from "./components/AnimatedText";
import HireMe from "./components/HireMe";
import Link from "next/link";
import { LinkArrow } from "./components/Icons";
import LightBulb from "@/public/miscellaneous_icons_1.svg"
import TransitionEffect from "./components/TransitionEffect"

export const metadata = {
  title: "OUTBREAK | Portfolio",
  description: "Generated by Nikhil Mishra",
};


export default function Home() {  
  return (
    <>
    <TransitionEffect />

    <main className="bg-white w-full items-center text-black flex min-h-screen flex-col  xl:p-20 lg:p-14 md:p-10 sm:p-6 dark:bg-dark dark:text-white">
      {/* <Navbar /> */}
      <div className="pt-0 sm:pt-8">
        <div className="flex items-center justify-evenly w-full lg:flex-col">
          <div className="w-1/2 md:w-[50%]">
            <Image
              src={MainPic}
              alt="Image"
              className="ml-32 h-auto xl:ml-0 xl:w-[75%] lg:hidden md:inline-block md:w-full pt-4"
              priority
              sizes="(max-width: 768px) 100vw, (max-width:1000px) 50vw, 50vw"
            />
          </div>
          <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center ">
            <AnimatedText
              text="Developing the new project is always exciting and fun."
              className="!text-5xl !text-left xl:!4xl lg:!text-center lg:!6xl md:!text-3xl sm:!text-2xl lg:!mt-16"
            />
            <p className="my-4 mt-4 text-base font-medium md:text-sm sm:text-xs">
              As a Student, I am addicted to trying the new idea into reality in
              web application. Explore my portfolio and articles to known more
              about me and my Projects. This is mainly developed by React.Js and
              Next.js and i am trying to be a Full Stack developer by making
              multiple projects and showcasing my skills to everyone.
            </p>
            <div className="flex items-center self-start mt-3 lg:self-center">
              <Link
                href="/dummy.pdf"
                target={"_blank"}
                className="bg-black flex flex-row dark:bg-white dark:text-dark dark:hover:bg-dark dark:hover:text-white dark:hover:border-white text-white hover:bg-white hover:text-black hover:border-2 hover:border-gray-700 px-4 py-3 rounded-md font-bold text-xl mx-3 md:p-2 md:px-4 md:text-base"
                download={true}
              >
                Resume <LinkArrow className={"w-6 ml-3 font-thin "}>
                </LinkArrow>
              </Link>
              <a
                href="mailto:mishran.2003@gmail.com"
                target="_blank"
                className="font-bold text-xl ml-3 px-4 py-3 dark:text-white dark:hover:no-underline dark:hover:border-white uppercase rounded-md underline underline-offset-2 hover:border-2 hover:border-gray-700 hover:no-underline transition-all ease-in-out"
              >
                Contacts
              </a>
            </div>
          </div>
        </div>
      </div>
      <HireMe />
      <div className="absolute right-8 bottom-12 inline-block w-24 md:hidden">
        <Image src={LightBulb} alt="Image" className="w-full h-auto" />
      </div>
    </main>

    </>
  );
}

