"use client";

import React, { useRef } from "react";
import AnimatedText from "../components/AnimatedText";
import Link from "next/link";
import Image from "next/image";
import sages from "../../public/sages.jpg";
import cloud from "../../public/cloudComputing.jpg";
import { motion, useMotionValue } from "framer-motion";
import TransitionEffect from "../components/TransitionEffect";

import dna from "../../public/dna1.jpg";
import moon from "../../public/moon.avif";
import Ramershwaram from "../../public/ramTemple.jpg";
import social from "../../public/social.jpg";
import nature from "../../public/nature.jpg";
import poll from "../../public/poll.jpg";
import space from "../../public/universe.jpeg";


export const metadata = {
  title: "OUTBREAK | Articles",
  description: "Generated by Nikhil Mishra",
};

const FramerImage = motion(Image);

const FeatureArticle = ({ img, title, summay, time, link }) => {
  return (
    <li className="col-span-1 w-[85%] ml-7 lg:ml-4 md:ml-5 sm:ml-3 xs:ml-2 p-4 bg-white border border-solid border-black/90 rounded-2xl relative dark:bg-dark dark:border-light">
      <div className="absolute top-0 -right-4 -z-10 w-[102%] h-[103%] rounded-[2rem] rounded-br-3xl bg-black dark:bg-light" />

      <Link
        href={link}
        target="_blank"
        className="w-full cursor-pointer overflow-hidden rounded-lg"
      >
        <FramerImage
          whileHover={{ scale: 1.02 }}
          transition={{ duration: 0.2 }}
          src={img}
          alt={title}
          className="w-full h-auto rounded-lg"
        />
      </Link>
      <Link href={link} target="_blank">
        <h2 className="capitalize text-2xl hover:underline hover:underline-offset-2 xs:text-lg font-bold my-2 mt-6 text-primary dark:text-primaryDark">
          {title}
        </h2>
      </Link>
      <p className="text-md mb-2 line-clamp-2 xs:text-sm">{summay}</p>
      <div className="flex items-center justify-between">
        <span className="tet-primary font-semibold">{time}</span>
        <Link
          href={link}
          target="_blank"
          className="ml-4 font-medium text-2xl mr-12 underline underline-offset-2 dark:text-light"
        >
          Visit
        </Link>
      </div>
    </li>
  );
};
const TodayDate = new Date().toISOString().slice(0, 10);

const Article = ({ img, title, date, link }) => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const imgRef = useRef(null);

  function handleMouse(e) {
    imgRef.current.style.display = "inline-block";
    x.set(e.pageX);
    y.set(-10);
  }
  function handleMouseLeave() {
    imgRef.current.style.display = "none";
    x.set(0);
    y.set(0);
  }

  return (
    <Link
      href={link}
      onMouseMove={handleMouse}
      onMouseLeave={handleMouseLeave}
      target="_blank"
    >
      <motion.li
        initial={{ y: 200 }}
        whileInView={{ y: 0, transition: { duration: 0.8, ease: "easeInOut" } }}
        viewport={{ once: true }}
        className="relative w-[100%] py-6 mx-2 my-6 p-4 rounded-xl flex items-center justify-between bg-white text-black dark:text-light dark:bg-dark dark:border-light first:mt-0 border border-solid border-r-4 border-b-4 sm:flex-col border-black"
      >
        <h2 className="capitalize text-2xl font-semibold hover:underline underline-offset-4 sm:text-xl">
          {title}
        </h2>
        <FramerImage
          whileInView={{ opacity: 0.9, duration: 0.9, ease: "easeInOut" }}
          viewport={{ once: true }}
          style={{ x: x, y: y }}
          ref={imgRef}
          src={img}
          alt={title}
          priority
          sizes="(max-width: 768px) 100vw, (max-width:1000px) 50vw, 50vw"
          className="w-96 z-10 h-auto hidden absolute rounded-xl md:!hidden "
        />
        <span className="font-semibold text-primary dark:text-primaryDark sm:self-start">
          {date}
        </span>
      </motion.li>
    </Link>
  );
};

const page = () => {
  return (
    <div>
                <TransitionEffect />
      <main className="w-full flex flex-col items-center justify-center overflow-hidden dark:text-white">
        <div className="pt-12">
          <AnimatedText
            className="py-20 lg:!text-8xl md:!text-6xl sm:!text-4xl xs:!text-3xl"
            text="Revealing my Creative Journey"
          />{" "}
          <ul className="grid grid-cols-2 gap-12 lg:gap-8 md:grid-cols-1 md:gap-y-16 lg:ml-8 sm:ml-6">
            <FeatureArticle
              title="Ancient Sages of India"
              summay="They left behind a rich legacy of scriptures, including the Vedas, Upanishads, and various philosophical treatises, which continue to influence spirituality, philosophy, and yoga worldwide. Their teachings emphasized the pursuit of inner wisdom, ethical living, and the interconnectedness of all life."
              time="12 min read"
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/sages-of-india"
              img={sages}
            />
            <FeatureArticle
              title="Future of Cloud Database"
              summay="The future of cloud databases is poised for remarkable growth and innovation. Scalability and performance enhancements will remain a priority, with a focus on optimizing distributed database technologies for handling massive datasets and high-performance applications. Serverless databases will become increasingly popular, offering automatic scaling and reduced management overhead."
              time="8 min read"
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/sages-of-india"
              img={cloud}
            />
          </ul>
          <h2 className="font-bold w-full text-center my-12 mt-24 grid grid-cols-2 lg:grid-cols-1">
            <div className="text-6xl mr-12 underline underline-offset-8 xl:text-5xl xl:underline-offset-[8px] lg:text-4xl md:text-3xl md:ml-14 sm:text-2xl sm:ml-8">
              My Blog Articles
            </div>
            <Link
              href="https://sanity-blog-nextjs-outbreak778.vercel.app/"
              target="_blank"
            >
              <div className="absolute w-auto right-24 items-end border px-4 py-3 rounded-xl  border-black border-solid border-r-4 border-b-4 text-xl dark:border-light dark:text-white dark:bg-dark lg:my-4 lg:right-10 lg:w-[90%] lg:text-center md:right-16 md:w-[80%] xs:right-8">
                Visit My Blogs
              </div>
            </Link>
          </h2>
          <ul className="w-full p-12 mb-12 sm:-ml-2">
            <Article
              title="Journey of India to Moon"
              img={moon}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/moon-mission-of-india"
            />
            <Article
              title="Increasing Pollution of Delhi"
              img={poll}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/pollution-of-delhi"
            />
            <Article
              title="The Wealthiest Temple - Rameshwaram Temple"
              img={Ramershwaram}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/rameshvaram-temple"
            />
            <Article
              title="World of Social Media "
              img={social}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/world-of-social-media"
            />
            <Article
              title="What does the DNA mean ?"
              img={dna}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/dna"
            />
            <Article
              title="Unexploreable thing is the Universe"
              img={space}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/wonder-of-universe"
            />
            <Article
              title="The beauty and power of Nature"
              img={nature}
              date={TodayDate}
              link="https://sanity-blog-nextjs-outbreak778.vercel.app/post/power-of-nature"
            />
          </ul>
        </div>
      </main>
    </div>
  );
};

export default page;
